version: '3.8'

services:
  mysql-db:
    image: mysql:8
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Eccommer
      MYSQL_USER: Eccommer
      MYSQL_PASSWORD: 123456
    ports:
      - "3456:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - shared-network
volumes:
  mysql_data:

networks:
  shared-network:
    driver: bridge
